const cdn = (char: string): string =>
  `https://emojicdn.elk.sh/${encodeURIComponent(char)}?style=apple`;

export interface Emoji {
  ch: string;
  url: string;
  label: string;
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: Emoji[];
}

const make = (chars: Array<[string, string]>): Emoji[] =>
  chars.map(([ch, label]) => ({ ch, url: cdn(ch), label }));

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: make([
      ['😀', 'Grinning'],
      ['😃', 'Smile'],
      ['😄', 'Big smile'],
      ['😁', 'Beaming'],
      ['😆', 'Grinning eyes'],
      ['😅', 'Sweat'],
      ['🤣', 'ROFL'],
      ['😂', 'Joy'],
      ['🙂', 'Slight smile'],
      ['🙃', 'Upside down'],
      ['😉', 'Wink'],
      ['😊', 'Blush'],
      ['😇', 'Halo'],
      ['🥰', 'Loved'],
      ['😍', 'Heart eyes'],
      ['🤩', 'Star struck'],
      ['😘', 'Kiss'],
      ['😗', 'Kissing'],
      ['☺️', 'Smiling'],
      ['😚', 'Closed kiss'],
      ['😙', 'Kiss eyes'],
      ['🥲', 'Smiling tear'],
      ['😋', 'Yum'],
      ['😛', 'Tongue'],
      ['😜', 'Tongue wink'],
      ['🤪', 'Zany'],
      ['😝', 'Squint tongue'],
      ['🤑', 'Money mouth'],
      ['🤗', 'Hug'],
      ['🤭', 'Hand mouth'],
      ['🫢', 'Open hand mouth'],
      ['🫣', 'Peek'],
      ['🤫', 'Shush'],
      ['🤔', 'Think'],
      ['🫡', 'Salute'],
      ['🤐', 'Zipper'],
      ['🤨', 'Raised brow'],
      ['😐', 'Neutral'],
      ['😑', 'Expressionless'],
      ['😶', 'No mouth'],
      ['🫥', 'Dotted line'],
      ['😏', 'Smirk'],
      ['😒', 'Unamused'],
      ['🙄', 'Eye roll'],
      ['😬', 'Grimace'],
      ['😮‍💨', 'Exhale'],
      ['🤥', 'Liar'],
      ['🫨', 'Shaking'],
      ['😌', 'Relieved'],
      ['😔', 'Pensive'],
      ['😪', 'Sleepy'],
      ['🤤', 'Drool'],
      ['😴', 'Sleep'],
      ['😷', 'Mask'],
      ['🤒', 'Thermometer'],
      ['🤕', 'Bandage'],
      ['🤢', 'Nauseated'],
      ['🤮', 'Vomit'],
      ['🤧', 'Sneeze'],
      ['🥵', 'Hot'],
      ['🥶', 'Cold'],
      ['🥴', 'Woozy'],
      ['😵', 'Dizzy'],
      ['😵‍💫', 'Spiral eyes'],
      ['🤯', 'Mind blown'],
      ['🤠', 'Cowboy'],
      ['🥳', 'Party'],
      ['🥸', 'Disguise'],
      ['😎', 'Cool'],
      ['🤓', 'Nerd'],
      ['🧐', 'Monocle'],
      ['😕', 'Confused'],
      ['🫤', 'Diagonal mouth'],
      ['😟', 'Worried'],
      ['🙁', 'Frown'],
      ['☹️', 'Sad'],
      ['😮', 'Open mouth'],
      ['😯', 'Hushed'],
      ['😲', 'Astonished'],
      ['😳', 'Flushed'],
      ['🥺', 'Pleading'],
      ['🥹', 'Holding tears'],
      ['😦', 'Frown open'],
      ['😧', 'Anguished'],
      ['😨', 'Fearful'],
      ['😰', 'Anxious'],
      ['😥', 'Sad relief'],
      ['😢', 'Cry'],
      ['😭', 'Sob'],
      ['😱', 'Scream'],
      ['😖', 'Confounded'],
      ['😣', 'Persevere'],
      ['😞', 'Disappoint'],
      ['😓', 'Sweat'],
      ['😩', 'Weary'],
      ['😫', 'Tired'],
      ['🥱', 'Yawn'],
      ['😤', 'Triumph'],
      ['😡', 'Pout'],
      ['😠', 'Angry'],
      ['🤬', 'Cursing'],
      ['😈', 'Smiling devil'],
      ['👿', 'Angry devil'],
      ['💀', 'Skull'],
      ['☠️', 'Skull bones'],
      ['💩', 'Poop'],
      ['🤡', 'Clown'],
      ['👹', 'Ogre'],
      ['👺', 'Goblin'],
      ['👻', 'Ghost'],
      ['👽', 'Alien'],
      ['👾', 'Space invader'],
      ['🤖', 'Robot'],
      ['😺', 'Cat smile'],
      ['😸', 'Cat grin'],
      ['😹', 'Cat tears'],
      ['😻', 'Cat hearts'],
      ['😼', 'Cat smirk'],
      ['😽', 'Cat kiss'],
      ['🙀', 'Cat scream'],
      ['😿', 'Cat cry'],
      ['😾', 'Cat pout'],
    ]),
  },
  {
    id: 'hearts',
    name: 'Hearts & Symbols',
    icon: '❤️',
    emojis: make([
      ['❤️', 'Red heart'],
      ['🧡', 'Orange heart'],
      ['💛', 'Yellow heart'],
      ['💚', 'Green heart'],
      ['💙', 'Blue heart'],
      ['💜', 'Purple heart'],
      ['🖤', 'Black heart'],
      ['🤍', 'White heart'],
      ['🤎', 'Brown heart'],
      ['💔', 'Broken'],
      ['❤️‍🔥', 'Heart fire'],
      ['❤️‍🩹', 'Mending'],
      ['💕', 'Two hearts'],
      ['💞', 'Revolving'],
      ['💓', 'Beating'],
      ['💗', 'Growing'],
      ['💖', 'Sparkling'],
      ['💘', 'Heart arrow'],
      ['💝', 'Heart ribbon'],
      ['💟', 'Heart decoration'],
      ['♥️', 'Hearts'],
      ['💯', '100'],
      ['💢', 'Anger'],
      ['💥', 'Boom'],
      ['💫', 'Dizzy'],
      ['💦', 'Sweat drops'],
      ['💨', 'Dash'],
      ['🕳️', 'Hole'],
      ['💣', 'Bomb'],
      ['💬', 'Speech'],
      ['👁️‍🗨️', 'Eye speech'],
      ['🗨️', 'Left speech'],
      ['🗯️', 'Anger speech'],
      ['💭', 'Thought'],
      ['💤', 'Z'],
      ['✨', 'Sparkles'],
      ['🌟', 'Glowing star'],
      ['⭐', 'Star'],
      ['⚡', 'Lightning'],
      ['🌈', 'Rainbow'],
      ['☄️', 'Comet'],
      ['🔥', 'Fire'],
    ]),
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: '👋',
    emojis: make([
      ['👋', 'Wave'],
      ['🤚', 'Back hand'],
      ['🖐️', 'Splayed'],
      ['✋', 'Raised'],
      ['🖖', 'Vulcan'],
      ['🫱', 'Right'],
      ['🫲', 'Left'],
      ['🫳', 'Down'],
      ['🫴', 'Up'],
      ['👌', 'OK'],
      ['🤌', 'Pinched'],
      ['🤏', 'Pinching'],
      ['✌️', 'Victory'],
      ['🤞', 'Crossed'],
      ['🫰', 'Heart fingers'],
      ['🤟', 'Love'],
      ['🤘', 'Rock'],
      ['🤙', 'Call me'],
      ['👈', 'Left point'],
      ['👉', 'Right point'],
      ['👆', 'Up point'],
      ['🖕', 'Middle'],
      ['👇', 'Down point'],
      ['☝️', 'Index'],
      ['🫵', 'You'],
      ['👍', 'Thumbs up'],
      ['👎', 'Thumbs down'],
      ['✊', 'Fist'],
      ['👊', 'Punch'],
      ['🤛', 'Left fist'],
      ['🤜', 'Right fist'],
      ['👏', 'Clap'],
      ['🙌', 'Raise both'],
      ['🫶', 'Heart hands'],
      ['👐', 'Open hands'],
      ['🤲', 'Palms up'],
      ['🤝', 'Handshake'],
      ['🙏', 'Pray'],
      ['✍️', 'Writing'],
      ['💅', 'Nail polish'],
      ['🤳', 'Selfie'],
      ['💪', 'Muscle'],
      ['🦾', 'Mechanical arm'],
      ['🦿', 'Mechanical leg'],
      ['🦵', 'Leg'],
      ['🦶', 'Foot'],
      ['👂', 'Ear'],
      ['🦻', 'Hearing aid'],
      ['👃', 'Nose'],
      ['🧠', 'Brain'],
      ['🫀', 'Heart organ'],
      ['🫁', 'Lungs'],
      ['🦷', 'Tooth'],
      ['🦴', 'Bone'],
      ['👀', 'Eyes'],
      ['👁️', 'Eye'],
      ['👅', 'Tongue'],
      ['👄', 'Mouth'],
      ['🫦', 'Biting lip'],
      ['👶', 'Baby'],
      ['🧒', 'Child'],
      ['👦', 'Boy'],
      ['👧', 'Girl'],
      ['🧑', 'Person'],
      ['👨', 'Man'],
      ['👩', 'Woman'],
      ['🧓', 'Older'],
      ['👴', 'Old man'],
      ['👵', 'Old woman'],
      ['👼', 'Angel'],
      ['🎅', 'Santa'],
      ['🤶', 'Mrs Claus'],
      ['🦸', 'Hero'],
      ['🦹', 'Villain'],
      ['🧙', 'Mage'],
      ['🧚', 'Fairy'],
      ['🧛', 'Vampire'],
      ['🧜', 'Merperson'],
      ['🧝', 'Elf'],
      ['🧞', 'Genie'],
      ['🧟', 'Zombie'],
    ]),
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: make([
      ['🐶', 'Dog'],
      ['🐱', 'Cat'],
      ['🐭', 'Mouse'],
      ['🐹', 'Hamster'],
      ['🐰', 'Rabbit'],
      ['🦊', 'Fox'],
      ['🐻', 'Bear'],
      ['🐼', 'Panda'],
      ['🐻‍❄️', 'Polar bear'],
      ['🐨', 'Koala'],
      ['🐯', 'Tiger'],
      ['🦁', 'Lion'],
      ['🐮', 'Cow'],
      ['🐷', 'Pig'],
      ['🐽', 'Pig nose'],
      ['🐸', 'Frog'],
      ['🐵', 'Monkey'],
      ['🙈', 'See no evil'],
      ['🙉', 'Hear no evil'],
      ['🙊', 'Speak no evil'],
      ['🐒', 'Monkey full'],
      ['🐔', 'Chicken'],
      ['🐧', 'Penguin'],
      ['🐦', 'Bird'],
      ['🐤', 'Chick'],
      ['🐣', 'Hatching'],
      ['🐥', 'Front chick'],
      ['🦆', 'Duck'],
      ['🦅', 'Eagle'],
      ['🦉', 'Owl'],
      ['🦇', 'Bat'],
      ['🐺', 'Wolf'],
      ['🐗', 'Boar'],
      ['🐴', 'Horse face'],
      ['🦄', 'Unicorn'],
      ['🐝', 'Bee'],
      ['🐛', 'Bug'],
      ['🦋', 'Butterfly'],
      ['🐌', 'Snail'],
      ['🐞', 'Lady beetle'],
      ['🐜', 'Ant'],
      ['🪰', 'Fly'],
      ['🕷️', 'Spider'],
      ['🦂', 'Scorpion'],
      ['🐢', 'Turtle'],
      ['🐍', 'Snake'],
      ['🦎', 'Lizard'],
      ['🦖', 'T-Rex'],
      ['🦕', 'Sauropod'],
      ['🐙', 'Octopus'],
      ['🦑', 'Squid'],
      ['🦐', 'Shrimp'],
      ['🦞', 'Lobster'],
      ['🦀', 'Crab'],
      ['🐡', 'Blowfish'],
      ['🐠', 'Tropical fish'],
      ['🐟', 'Fish'],
      ['🐬', 'Dolphin'],
      ['🐳', 'Whale'],
      ['🐋', 'Whale 2'],
      ['🦈', 'Shark'],
      ['🐊', 'Crocodile'],
      ['🐅', 'Tiger 2'],
      ['🐆', 'Leopard'],
      ['🦓', 'Zebra'],
      ['🦍', 'Gorilla'],
      ['🦧', 'Orangutan'],
      ['🐘', 'Elephant'],
      ['🦣', 'Mammoth'],
      ['🦛', 'Hippo'],
      ['🦏', 'Rhino'],
      ['🐪', 'Camel'],
      ['🐫', 'Two-hump'],
      ['🦒', 'Giraffe'],
      ['🦘', 'Kangaroo'],
      ['🐃', 'Buffalo'],
      ['🐂', 'Ox'],
      ['🐄', 'Cow 2'],
      ['🐎', 'Horse'],
      ['🐖', 'Pig 2'],
      ['🐏', 'Ram'],
      ['🐑', 'Sheep'],
      ['🦙', 'Llama'],
      ['🐐', 'Goat'],
      ['🦌', 'Deer'],
      ['🐕', 'Dog 2'],
      ['🐩', 'Poodle'],
      ['🦮', 'Guide dog'],
      ['🐈', 'Cat 2'],
      ['🐓', 'Rooster'],
      ['🦃', 'Turkey'],
      ['🦚', 'Peacock'],
      ['🦜', 'Parrot'],
      ['🦢', 'Swan'],
      ['🦩', 'Flamingo'],
      ['🕊️', 'Dove'],
      ['🐇', 'Rabbit 2'],
      ['🦝', 'Raccoon'],
      ['🦨', 'Skunk'],
      ['🦡', 'Badger'],
      ['🐾', 'Paw prints'],
      ['🌵', 'Cactus'],
      ['🎄', 'Tree'],
      ['🌲', 'Evergreen'],
      ['🌳', 'Deciduous'],
      ['🌴', 'Palm'],
      ['🌱', 'Seedling'],
      ['🌿', 'Herb'],
      ['☘️', 'Shamrock'],
      ['🍀', 'Clover'],
      ['🍁', 'Maple'],
      ['🍂', 'Fallen'],
      ['🍃', 'Wind'],
      ['🌷', 'Tulip'],
      ['🌹', 'Rose'],
      ['🥀', 'Wilted'],
      ['🌺', 'Hibiscus'],
      ['🌸', 'Cherry blossom'],
      ['🌼', 'Daisy'],
      ['🌻', 'Sunflower'],
      ['🌞', 'Sun face'],
      ['🌝', 'Full moon face'],
      ['🌚', 'New moon face'],
      ['🌜', 'Moon'],
    ]),
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍔',
    emojis: make([
      ['🍏', 'Green apple'],
      ['🍎', 'Red apple'],
      ['🍐', 'Pear'],
      ['🍊', 'Tangerine'],
      ['🍋', 'Lemon'],
      ['🍌', 'Banana'],
      ['🍉', 'Watermelon'],
      ['🍇', 'Grapes'],
      ['🍓', 'Strawberry'],
      ['🫐', 'Blueberries'],
      ['🍈', 'Melon'],
      ['🍒', 'Cherries'],
      ['🍑', 'Peach'],
      ['🥭', 'Mango'],
      ['🍍', 'Pineapple'],
      ['🥥', 'Coconut'],
      ['🥝', 'Kiwi'],
      ['🍅', 'Tomato'],
      ['🍆', 'Eggplant'],
      ['🥑', 'Avocado'],
      ['🥦', 'Broccoli'],
      ['🥬', 'Greens'],
      ['🥒', 'Cucumber'],
      ['🌶️', 'Pepper'],
      ['🫑', 'Bell pepper'],
      ['🌽', 'Corn'],
      ['🥕', 'Carrot'],
      ['🫒', 'Olive'],
      ['🧄', 'Garlic'],
      ['🧅', 'Onion'],
      ['🥔', 'Potato'],
      ['🍠', 'Sweet potato'],
      ['🥐', 'Croissant'],
      ['🥯', 'Bagel'],
      ['🍞', 'Bread'],
      ['🥖', 'Baguette'],
      ['🫓', 'Flatbread'],
      ['🥨', 'Pretzel'],
      ['🧀', 'Cheese'],
      ['🥚', 'Egg'],
      ['🍳', 'Frying egg'],
      ['🧈', 'Butter'],
      ['🥞', 'Pancakes'],
      ['🧇', 'Waffle'],
      ['🥓', 'Bacon'],
      ['🥩', 'Steak'],
      ['🍗', 'Drumstick'],
      ['🍖', 'Meat'],
      ['🦴', 'Bone'],
      ['🌭', 'Hot dog'],
      ['🍔', 'Burger'],
      ['🍟', 'Fries'],
      ['🍕', 'Pizza'],
      ['🥪', 'Sandwich'],
      ['🥙', 'Stuffed'],
      ['🧆', 'Falafel'],
      ['🌮', 'Taco'],
      ['🌯', 'Burrito'],
      ['🫔', 'Tamale'],
      ['🥗', 'Salad'],
      ['🥘', 'Pan'],
      ['🫕', 'Fondue'],
      ['🥫', 'Canned'],
      ['🍝', 'Pasta'],
      ['🍜', 'Noodles'],
      ['🍲', 'Pot'],
      ['🍛', 'Curry'],
      ['🍣', 'Sushi'],
      ['🍱', 'Bento'],
      ['🥟', 'Dumpling'],
      ['🦪', 'Oyster'],
      ['🍤', 'Shrimp tempura'],
      ['🍙', 'Rice ball'],
      ['🍚', 'Rice'],
      ['🍘', 'Rice cracker'],
      ['🍥', 'Fish cake'],
      ['🥮', 'Mooncake'],
      ['🍢', 'Oden'],
      ['🍡', 'Dango'],
      ['🍧', 'Shaved ice'],
      ['🍨', 'Ice cream'],
      ['🍦', 'Soft serve'],
      ['🥧', 'Pie'],
      ['🧁', 'Cupcake'],
      ['🍰', 'Cake slice'],
      ['🎂', 'Birthday cake'],
      ['🍮', 'Custard'],
      ['🍭', 'Lollipop'],
      ['🍬', 'Candy'],
      ['🍫', 'Chocolate'],
      ['🍿', 'Popcorn'],
      ['🍩', 'Donut'],
      ['🍪', 'Cookie'],
      ['🌰', 'Chestnut'],
      ['🥜', 'Peanuts'],
      ['🍯', 'Honey'],
      ['🥛', 'Milk'],
      ['🍼', 'Bottle'],
      ['☕', 'Coffee'],
      ['🍵', 'Tea'],
      ['🧃', 'Juice box'],
      ['🥤', 'Cup straw'],
      ['🧋', 'Bubble tea'],
      ['🍶', 'Sake'],
      ['🍺', 'Beer'],
      ['🍻', 'Beers'],
      ['🥂', 'Champagne'],
      ['🍷', 'Wine'],
      ['🥃', 'Whiskey'],
      ['🍸', 'Cocktail'],
      ['🍹', 'Tropical'],
      ['🍾', 'Bottle pop'],
      ['🧉', 'Mate'],
      ['🧊', 'Ice'],
      ['🥄', 'Spoon'],
      ['🍴', 'Fork knife'],
      ['🍽️', 'Plate'],
      ['🥢', 'Chopsticks'],
      ['🧂', 'Salt'],
    ]),
  },
  {
    id: 'activities',
    name: 'Activities',
    icon: '⚽',
    emojis: make([
      ['⚽', 'Soccer'],
      ['🏀', 'Basketball'],
      ['🏈', 'Football'],
      ['⚾', 'Baseball'],
      ['🥎', 'Softball'],
      ['🎾', 'Tennis'],
      ['🏐', 'Volleyball'],
      ['🏉', 'Rugby'],
      ['🥏', 'Disc'],
      ['🎱', 'Pool'],
      ['🪀', 'Yo-yo'],
      ['🏓', 'Ping pong'],
      ['🏸', 'Badminton'],
      ['🏒', 'Hockey'],
      ['🏑', 'Field hockey'],
      ['🥍', 'Lacrosse'],
      ['🏏', 'Cricket'],
      ['🪃', 'Boomerang'],
      ['🥅', 'Goal'],
      ['⛳', 'Flag in hole'],
      ['🪁', 'Kite'],
      ['🏹', 'Bow'],
      ['🎣', 'Fishing'],
      ['🤿', 'Diving'],
      ['🥊', 'Boxing'],
      ['🥋', 'Martial arts'],
      ['🎽', 'Running'],
      ['🛹', 'Skateboard'],
      ['🛼', 'Roller skate'],
      ['🛷', 'Sled'],
      ['⛸️', 'Ice skate'],
      ['🥌', 'Curling'],
      ['🎿', 'Skis'],
      ['⛷️', 'Skier'],
      ['🏂', 'Snowboard'],
      ['🪂', 'Parachute'],
      ['🏋️', 'Lifter'],
      ['🤼', 'Wrestling'],
      ['🤸', 'Cartwheel'],
      ['⛹️', 'Bouncing'],
      ['🤺', 'Fencing'],
      ['🤾', 'Handball'],
      ['🏌️', 'Golfer'],
      ['🏇', 'Horse race'],
      ['🧘', 'Yoga'],
      ['🏄', 'Surfing'],
      ['🏊', 'Swim'],
      ['🤽', 'Water polo'],
      ['🚣', 'Row'],
      ['🧗', 'Climb'],
      ['🚵', 'Mountain bike'],
      ['🚴', 'Cyclist'],
      ['🏆', 'Trophy'],
      ['🥇', 'Gold'],
      ['🥈', 'Silver'],
      ['🥉', 'Bronze'],
      ['🏅', 'Medal'],
      ['🎖️', 'Military'],
      ['🎗️', 'Ribbon'],
      ['🎫', 'Ticket'],
      ['🎟️', 'Admission'],
      ['🎪', 'Circus'],
      ['🤹', 'Juggling'],
      ['🎭', 'Theater'],
      ['🩰', 'Ballet'],
      ['🎨', 'Art'],
      ['🎬', 'Clapper'],
      ['🎤', 'Mic'],
      ['🎧', 'Headphone'],
      ['🎼', 'Score'],
      ['🎹', 'Piano'],
      ['🥁', 'Drum'],
      ['🪘', 'Long drum'],
      ['🎷', 'Sax'],
      ['🎺', 'Trumpet'],
      ['🎸', 'Guitar'],
      ['🪕', 'Banjo'],
      ['🎻', 'Violin'],
      ['🪗', 'Accordion'],
      ['🎲', 'Dice'],
      ['♟️', 'Chess'],
      ['🎯', 'Bullseye'],
      ['🎳', 'Bowling'],
      ['🎮', 'Gamepad'],
      ['🎰', 'Slot'],
      ['🧩', 'Puzzle'],
    ]),
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '✈️',
    emojis: make([
      ['🚗', 'Car'],
      ['🚕', 'Taxi'],
      ['🚙', 'SUV'],
      ['🚌', 'Bus'],
      ['🚎', 'Trolley'],
      ['🏎️', 'Racing car'],
      ['🚓', 'Police'],
      ['🚑', 'Ambulance'],
      ['🚒', 'Fire engine'],
      ['🚐', 'Minibus'],
      ['🛻', 'Pickup'],
      ['🚚', 'Truck'],
      ['🚛', 'Semi'],
      ['🚜', 'Tractor'],
      ['🛵', 'Scooter'],
      ['🏍️', 'Motorcycle'],
      ['🛺', 'Auto rickshaw'],
      ['🚲', 'Bicycle'],
      ['🛴', 'Kick scooter'],
      ['🛹', 'Skateboard'],
      ['🚨', 'Police light'],
      ['⛽', 'Fuel'],
      ['🚧', 'Construction'],
      ['🛞', 'Wheel'],
      ['🚏', 'Bus stop'],
      ['🗺️', 'Map'],
      ['🗿', 'Moai'],
      ['🗽', 'Liberty'],
      ['🗼', 'Tokyo tower'],
      ['🏰', 'Castle'],
      ['🏯', 'Japanese castle'],
      ['🏟️', 'Stadium'],
      ['🎡', 'Ferris wheel'],
      ['🎢', 'Roller coaster'],
      ['🎠', 'Carousel'],
      ['⛲', 'Fountain'],
      ['⛱️', 'Umbrella'],
      ['🏖️', 'Beach'],
      ['🏝️', 'Desert island'],
      ['🏜️', 'Desert'],
      ['🌋', 'Volcano'],
      ['⛰️', 'Mountain'],
      ['🏔️', 'Snow mountain'],
      ['🗻', 'Fuji'],
      ['🏕️', 'Camping'],
      ['⛺', 'Tent'],
      ['🏞️', 'National park'],
      ['🛣️', 'Motorway'],
      ['🛤️', 'Railway'],
      ['🌅', 'Sunrise'],
      ['🌄', 'Mountain sunrise'],
      ['🌠', 'Shooting star'],
      ['🌌', 'Milky way'],
      ['🎇', 'Sparkler'],
      ['🎆', 'Fireworks'],
      ['🌇', 'Cityscape dusk'],
      ['🌆', 'Cityscape'],
      ['🏙️', 'Cityscape day'],
      ['🌃', 'Night'],
      ['🌉', 'Bridge'],
      ['🌁', 'Foggy'],
      ['🚂', 'Locomotive'],
      ['🚆', 'Train'],
      ['🚇', 'Metro'],
      ['🚊', 'Tram'],
      ['🚉', 'Station'],
      ['✈️', 'Airplane'],
      ['🛩️', 'Small plane'],
      ['🛫', 'Takeoff'],
      ['🛬', 'Landing'],
      ['🪂', 'Parachute'],
      ['💺', 'Seat'],
      ['🚀', 'Rocket'],
      ['🛸', 'Saucer'],
      ['🚁', 'Helicopter'],
      ['🛶', 'Canoe'],
      ['⛵', 'Sailboat'],
      ['🚤', 'Speedboat'],
      ['🛥️', 'Motor boat'],
      ['🛳️', 'Cruise'],
      ['⛴️', 'Ferry'],
      ['🚢', 'Ship'],
      ['⚓', 'Anchor'],
      ['🪝', 'Hook'],
      ['⛽', 'Pump'],
      ['🚧', 'Barrier'],
    ]),
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: '💡',
    emojis: make([
      ['⌚', 'Watch'],
      ['📱', 'Phone'],
      ['📲', 'Phone arrow'],
      ['💻', 'Laptop'],
      ['⌨️', 'Keyboard'],
      ['🖥️', 'Desktop'],
      ['🖨️', 'Printer'],
      ['🖱️', 'Mouse'],
      ['🖲️', 'Trackball'],
      ['🕹️', 'Joystick'],
      ['🗜️', 'Clamp'],
      ['💽', 'Mini disc'],
      ['💾', 'Floppy'],
      ['💿', 'Optical'],
      ['📀', 'DVD'],
      ['📼', 'VHS'],
      ['📷', 'Camera'],
      ['📸', 'Camera flash'],
      ['📹', 'Video camera'],
      ['🎥', 'Movie camera'],
      ['📽️', 'Projector'],
      ['🎞️', 'Film frames'],
      ['📞', 'Telephone'],
      ['☎️', 'Old phone'],
      ['📟', 'Pager'],
      ['📠', 'Fax'],
      ['📺', 'TV'],
      ['📻', 'Radio'],
      ['🎙️', 'Studio mic'],
      ['🎚️', 'Slider'],
      ['🎛️', 'Knobs'],
      ['🧭', 'Compass'],
      ['⏱️', 'Stopwatch'],
      ['⏲️', 'Timer'],
      ['⏰', 'Alarm'],
      ['🕰️', 'Mantelpiece'],
      ['⌛', 'Hourglass'],
      ['⏳', 'Hourglass flow'],
      ['📡', 'Satellite dish'],
      ['🔋', 'Battery'],
      ['🪫', 'Low battery'],
      ['🔌', 'Plug'],
      ['💡', 'Bulb'],
      ['🔦', 'Flashlight'],
      ['🕯️', 'Candle'],
      ['🪔', 'Diya'],
      ['🧯', 'Extinguisher'],
      ['🛢️', 'Oil drum'],
      ['💸', 'Money fly'],
      ['💵', 'Dollar'],
      ['💴', 'Yen'],
      ['💶', 'Euro'],
      ['💷', 'Pound'],
      ['💰', 'Bag money'],
      ['💳', 'Credit'],
      ['💎', 'Gem'],
      ['⚖️', 'Scale'],
      ['🧰', 'Toolbox'],
      ['🔧', 'Wrench'],
      ['🔨', 'Hammer'],
      ['⚒️', 'Hammer pick'],
      ['🛠️', 'Tools'],
      ['⛏️', 'Pick'],
      ['🔩', 'Nut bolt'],
      ['⚙️', 'Gear'],
      ['🧱', 'Brick'],
      ['⛓️', 'Chains'],
      ['🧲', 'Magnet'],
      ['🔫', 'Pistol'],
      ['💣', 'Bomb'],
      ['🧨', 'Firecracker'],
      ['🪓', 'Axe'],
      ['🔪', 'Knife'],
      ['🗡️', 'Dagger'],
      ['⚔️', 'Crossed swords'],
      ['🛡️', 'Shield'],
      ['🚬', 'Cigarette'],
      ['⚰️', 'Coffin'],
      ['⚱️', 'Urn'],
      ['🏺', 'Amphora'],
      ['🔮', 'Crystal ball'],
      ['📿', 'Beads'],
      ['🧿', 'Nazar'],
      ['💈', 'Barber'],
      ['⚗️', 'Alembic'],
      ['🔭', 'Telescope'],
      ['🔬', 'Microscope'],
      ['🕳️', 'Hole'],
      ['💊', 'Pill'],
      ['💉', 'Syringe'],
      ['🩸', 'Blood'],
      ['🩹', 'Bandage'],
      ['🩺', 'Stethoscope'],
      ['🚪', 'Door'],
      ['🛗', 'Elevator'],
      ['🪞', 'Mirror'],
      ['🪟', 'Window'],
      ['🛏️', 'Bed'],
      ['🛋️', 'Couch'],
      ['🪑', 'Chair'],
      ['🚽', 'Toilet'],
      ['🪠', 'Plunger'],
      ['🚿', 'Shower'],
      ['🛁', 'Bathtub'],
      ['🧴', 'Bottle lotion'],
      ['🧷', 'Pin'],
      ['🧹', 'Broom'],
      ['🧺', 'Basket'],
      ['🧻', 'Tp'],
      ['🧼', 'Soap'],
      ['🧽', 'Sponge'],
      ['🪥', 'Toothbrush'],
      ['🪣', 'Bucket'],
      ['📝', 'Memo'],
      ['📋', 'Clipboard'],
      ['📌', 'Pushpin'],
      ['📍', 'Round pushpin'],
      ['📎', 'Paperclip'],
      ['📏', 'Ruler'],
      ['📐', 'Triangle ruler'],
      ['✂️', 'Scissors'],
      ['🖊️', 'Pen'],
      ['🖋️', 'Fountain pen'],
      ['✒️', 'Black pen'],
      ['🖌️', 'Brush'],
      ['🖍️', 'Crayon'],
      ['📔', 'Notebook decorative'],
      ['📕', 'Closed book'],
      ['📖', 'Open book'],
      ['📗', 'Green book'],
      ['📘', 'Blue book'],
      ['📙', 'Orange book'],
      ['📚', 'Books'],
      ['📓', 'Notebook'],
      ['📒', 'Ledger'],
      ['📃', 'Page curl'],
      ['📜', 'Scroll'],
      ['📄', 'Page'],
      ['📰', 'Newspaper'],
      ['📑', 'Bookmark tabs'],
      ['🔖', 'Bookmark'],
      ['🏷️', 'Label'],
      ['✉️', 'Envelope'],
      ['📧', 'Email'],
      ['📨', 'Inbox in'],
      ['📩', 'Inbox out'],
      ['📤', 'Outbox'],
      ['📥', 'Inbox'],
      ['📦', 'Package'],
      ['🎁', 'Gift'],
    ]),
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: '✅',
    emojis: make([
      ['✅', 'Check'],
      ['❌', 'Cross'],
      ['❎', 'Cross box'],
      ['✔️', 'Checkmark'],
      ['☑️', 'Ballot check'],
      ['❓', 'Question'],
      ['❔', 'White question'],
      ['❗', 'Exclamation'],
      ['❕', 'White exclamation'],
      ['⁉️', '!?'],
      ['‼️', '!!'],
      ['⚠️', 'Warning'],
      ['🚫', 'Prohibited'],
      ['⛔', 'No entry'],
      ['🚷', 'No pedestrians'],
      ['🚯', 'No littering'],
      ['🔞', 'No under 18'],
      ['☢️', 'Radioactive'],
      ['☣️', 'Biohazard'],
      ['⬆️', 'Up'],
      ['⬇️', 'Down'],
      ['⬅️', 'Left'],
      ['➡️', 'Right'],
      ['↗️', 'NE'],
      ['↘️', 'SE'],
      ['↙️', 'SW'],
      ['↖️', 'NW'],
      ['↕️', 'Up-down'],
      ['↔️', 'Left-right'],
      ['↪️', 'Right hook'],
      ['↩️', 'Left hook'],
      ['⤴️', 'Up flip'],
      ['⤵️', 'Down flip'],
      ['🔃', 'Clockwise'],
      ['🔄', 'Counterclockwise'],
      ['🔼', 'Up triangle'],
      ['🔽', 'Down triangle'],
      ['⏫', 'Fast up'],
      ['⏬', 'Fast down'],
      ['⏩', 'Fast forward'],
      ['⏪', 'Rewind'],
      ['▶️', 'Play'],
      ['◀️', 'Reverse'],
      ['⏯️', 'Play pause'],
      ['⏸️', 'Pause'],
      ['⏹️', 'Stop'],
      ['⏺️', 'Record'],
      ['♻️', 'Recycle'],
      ['⚜️', 'Fleur'],
      ['🔱', 'Trident'],
      ['⚛️', 'Atom'],
      ['☮️', 'Peace'],
      ['☯️', 'Yin yang'],
      ['🕉️', 'Om'],
      ['✝️', 'Cross'],
      ['☪️', 'Crescent'],
      ['♈', 'Aries'],
      ['♉', 'Taurus'],
      ['♊', 'Gemini'],
      ['♋', 'Cancer'],
      ['♌', 'Leo'],
      ['♍', 'Virgo'],
      ['♎', 'Libra'],
      ['♏', 'Scorpio'],
      ['♐', 'Sagittarius'],
      ['♑', 'Capricorn'],
      ['♒', 'Aquarius'],
      ['♓', 'Pisces'],
      ['⛎', 'Ophiuchus'],
      ['🔀', 'Shuffle'],
      ['🔁', 'Repeat'],
      ['🔂', 'Repeat one'],
      ['🔢', '1234'],
      ['🔡', 'abcd'],
      ['🔠', 'ABCD'],
      ['🔤', 'input latin'],
      ['♿', 'Wheelchair'],
      ['🚹', 'Men'],
      ['🚺', 'Women'],
      ['🚻', 'Restroom'],
      ['🚼', 'Baby'],
      ['🚾', 'WC'],
      ['🅿️', 'Parking'],
      ['🆒', 'Cool'],
      ['🆓', 'Free'],
      ['🆕', 'New'],
      ['🆗', 'OK'],
      ['🆙', 'Up'],
      ['🆚', 'VS'],
      ['🈁', 'Here'],
      ['🈯', 'Reserved'],
      ['💮', 'White flower'],
      ['🉐', 'Bargain'],
      ['㊙️', 'Secret'],
      ['㊗️', 'Congrats'],
      ['🈴', 'Pass'],
      ['🈵', 'Full'],
      ['🈲', 'Prohibited'],
      ['🅰️', 'A'],
      ['🅱️', 'B'],
      ['🆎', 'AB'],
      ['🆑', 'CL'],
      ['🅾️', 'O'],
      ['🆘', 'SOS'],
      ['🔴', 'Red circle'],
      ['🟠', 'Orange circle'],
      ['🟡', 'Yellow circle'],
      ['🟢', 'Green circle'],
      ['🔵', 'Blue circle'],
      ['🟣', 'Purple circle'],
      ['🟤', 'Brown circle'],
      ['⚫', 'Black circle'],
      ['⚪', 'White circle'],
      ['🟥', 'Red square'],
      ['🟧', 'Orange square'],
      ['🟨', 'Yellow square'],
      ['🟩', 'Green square'],
      ['🟦', 'Blue square'],
      ['🟪', 'Purple square'],
      ['🟫', 'Brown square'],
      ['⬛', 'Black square'],
      ['⬜', 'White square'],
      ['◼️', 'Med black'],
      ['◻️', 'Med white'],
      ['◾', 'Small black'],
      ['◽', 'Small white'],
      ['▪️', 'Tiny black'],
      ['▫️', 'Tiny white'],
    ]),
  },
];

export const findEmoji = (ch: string): Emoji | null => {
  for (const cat of EMOJI_CATEGORIES) {
    const found = cat.emojis.find((e) => e.ch === ch);
    if (found) return found;
  }
  return null;
};
